# Generated by Django 2.1.5 on 2019-03-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feeding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal', models.CharField(choices=[('B', 'Breakfast'), ('L', 'Lunch'), ('D', 'Dinner')], default='B', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='pokemon',
            name='age',
            field=models.IntegerField(default='SOME INT'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='attack',
            field=models.CharField(default='SOME CHAR', max_length=100),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='description',
            field=models.TextField(default='SOME TEXT', max_length=100),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='name',
            field=models.CharField(default='SOME CHAR', max_length=100),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='weakness',
            field=models.CharField(default='SOME CHAR', max_length=100),
        ),
    ]
