# Generated by Django 2.1.5 on 2019-03-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20190314_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
