# Generated by Django 2.1.5 on 2019-03-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20190314_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='age',
            field=models.IntegerField(),
        ),
    ]
